# Generated by Django 4.2.13 on 2024-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='productos_img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceUSD',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
